version: '3.7'

x-common: &common
    image: liofal/streamlink:1.8.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
        - ../global.env    
        - default.env
        - clientid.env
    user: 1027:100
    logging:
      driver: json-file
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
    - /volume1/twitch:/download

services:
#  test:
#     <<: *common
#     # volumes:
#     # - ./streamlink-recorder.py:/streamlink-recorder.py
#     # - /volume1/twitch:/download
#     # entrypoint: ping www.google.be
#     # user: root
#     environment:
#       - user=nl_kripp
#       - quality=worst
 
 starcraft:
    <<: *common
    environment:
      - user=starcraft
      - gamelist=496902
 
 maru072:
    <<: *common
    environment:
      - user=maru072
      - quality=best
 
 serral:
    <<: *common
    environment:
      - user=serral
      - quality=best

 rb_reynor:
    <<: *common
    environment:
      - user=rb_reynor

 n33bl3t:
    <<: *common
    environment:
      - user=n33bl3t
      - quality=best

 