x-common: &common
    user: 1027:100
    logging:
      driver: json-file
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
    - /volume1/twitch:/app/download

services:
  streamlink:
    <<: *common
    image: ghcr.io/liofal/streamlink:3.3.4
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: 
        # - ../global.env    
        - default.env
        - clientid.env
    container_name: streamlink_${TWITCH}
    environment:
      - user=${TWITCH}
      - quality=best
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  ffmpeg:
    <<: *common
    image: ghcr.io/liofal/ffmpeg6:1.0.0
    container_name: ffmpeg_converter
    environment:
      - SLEEPTIME=600
      - WORKDIR=/app/download
    
    restart: unless-stopped
