apiVersion: v2
name: streamlink-chart
description: A Helm chart for Kubernetes to run streamlink jobs for different streamers
type: application
version: 3.3.4
appVersion: 3.3.4
home: https://github.com/liofal/streamlink
sources:
  - https://github.com/liofal/streamlink
maintainers:
  - name: liofal
    email: lfa@gmx.com
    url: https://github.com/liofal
