name: Build docker images with reusable actions.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  deploy:
    uses: liofal/actions/.github/workflows/build_and_deploy.yml@main
    permissions:
      packages: write
    secrets: inherit